spring.application.name=bff
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.enabled=false
services.students.url=http://localhost:8081
services.attendance.url=http://localhost:8084
services.grades.url=http://localhost:8083
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
server.error.include-message=always
server.error.include-binding-errors=always
