services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: aulaboh-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8089:8080"
    volumes:
      - ./realms:/opt/keycloak/data/import
