CREATE TABLE school_classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    class_date DATE NOT NULL
);

CREATE TABLE attendances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    observation VARCHAR(255),
    CONSTRAINT fk_attendances_class
        FOREIGN KEY (class_id) REFERENCES school_classes (id),
    CONSTRAINT uk_attendances_class_student
        UNIQUE (class_id, student_id)
);
