CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    course VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    birth_date DATE,
    student_username VARCHAR(255),
    guardian_username VARCHAR(255),
    status VARCHAR(255) NOT NULL
);
