CREATE TABLE evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    evaluation_date DATE
);

CREATE TABLE grades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluation_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_grades_evaluation
        FOREIGN KEY (evaluation_id) REFERENCES evaluations (id)
);
